### ISSUE TITLE
`query(label='hippocampus', prefix='UBERON')`

### ISSUE THREAD

**Issue by bendichter** [tgbugs/ontquery#2]
'brain' and 'hypothalamus' work, but 'hippocampus' doesn't get any results. Do you know why that might be?

**Comment by tgbugs** [comment]
If you search `OntTerm(label='hippocampus')` you will got find results because label only returns exact matches does not search synonyms, `OntTerm(term='hippocampus')` will find 3 results. If you searched with term= and did not that is quite strange and I would want to know more.

One query pattern that I use frequently is to progressively broaden your search like this:
``` python
OntTerm(label='brain') 
OntTerm(term='brain')
OntTerm(search='brain')
```
Another pattern is to start broad and become more narrow:
``` python
OntTerm(term='brain')
OntTerm(label='brain')
```
(brain is not actually a case where either of these patterns are useful).

As a side note `hippocampus` without any qualifiers is one of the go to examples where the meaning of a term can vary significantly between fields.

**Comment by bendichter** [comment]
Thanks for clearing that up. Huh, interesting, I didn't know "hippocampus" was so contentious! That's why I like that the Allen Brain Atlas shows you an image of the region when you select terms.
